services:

  db_postgres:
    image: postgres:16-alpine
    container_name: db_postgres
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
      - ./database_schema.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=${DB_NAME:-mtuci_shop_detector}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - TZ=Europe/Moscow
    networks:
      shopnet:
        ipv4_address: 172.20.10.10

  app:
    build: .
    container_name: mtuci_shop_detector
    restart: always
    ports:
      - "8501:8501"
    depends_on:
      - db_postgres
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
    environment:
      - DB_HOST=db_postgres
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-mtuci_shop_detector}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DISPLAY=${DISPLAY:-:0}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    privileged: true
    networks:
      shopnet:
        ipv4_address: 172.20.10.20

networks:
  shopnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.35.254